version: "3.7"

services:
  db-receipt:
    image: postgres:14.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=receipt
  web-tomcat:
    image: tomcat:10.0.27
    volumes:
      - ./build/libs/clevertec.war:/usr/local/tomcat/webapps/clevertec.war
    ports:
      - 8080:8080