Insert Into product(quantity) values (2.12);
Insert Into product(quantity) values (15);
Insert Into product(quantity) values (4.86);
Insert Into product(quantity) values (8);
Insert Into product(quantity) values (6.41);
Insert Into product(quantity) values (8);
Insert Into product(quantity) values (15);
Insert Into product(quantity) values (22);
Insert Into product(quantity) values (12.83);
Insert Into product(quantity) values (6.48);
Insert Into product(quantity) values (14.5);
Insert Into product(quantity) values (21);

Insert INTO discount_card(number) values('15fd20181');
Insert INTO discount_card(number) values('15fd20182');
Insert INTO discount_card(number) values('15fd20183');
Insert INTO discount_card(number) values('15fd20184');
Insert INTO discount_card(number) values('15fd20185');
Insert INTO discount_card(number) values('15fd20186');
Insert INTO discount_card(number) values('15fd20187');
Insert INTO discount_card(number) values('15fd20188');
Insert INTO discount_card(number) values('15fd20189');